resource "local_file" "pet" {
  filename        = var.filename
  content         = "My faverite pet is ${random_pet.my-pet.id}."
  file_permission = 0777
}

resource "random_pet" "my-pet" {
  prefix    = var.prefix
  length    = var.length
  separator = var.separator
}

output "pet-name" {
  value       = random_pet.my-pet.id
  description = "Record the value of pet ID, generated by the random pet resource."
}